FROM node:12-alpine

MAINTAINER Nightscout Contributors

RUN mkdir -p /opt/app
ADD . /opt/app
WORKDIR /opt/app
RUN apk --no-cache add python make g++ && \
    chown -R node:node /opt/app
USER node

RUN npm install && \
  npm run postinstall && \
  npm run env && \
  npm audit fix

EXPOSE 1337

CMD ["node", "server.js"]
