// Browser D3 surface used by Nightscout charts and report plugins.
// Export transition explicitly to retain selection.transition/interrupt initialization.
export {
  arc,
  area,
  axisBottom,
  axisLeft,
  axisRight,
  brushSelection,
  brushX,
  color,
  curveStepAfter,
  drag,
  extent,
  format,
  interpolateRgb,
  line,
  max,
  pie,
  pointer,
  scaleLinear,
  scaleLog,
  scaleOrdinal,
  scaleTime,
  select,
  selectAll,
  timeDay,
  timeFormat,
  timeFormatLocale,
  timeHour,
  timeMinute,
  timeMonth,
  timeSecond,
  timeWeek,
  timeYear,
  transition
} from 'd3';
