name: Auto-close Accidental Sync PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-close sync PRs from forks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const baseRepo = pr.base.repo.full_name;
            const headRepo = pr.head.repo.full_name;
            const isFromFork = baseRepo !== headRepo;

            const syncIndicators = ["sync", "merge", "update", "pull", "new", "."];
            const title = pr.title.toLowerCase();
            const isLikelySync = syncIndicators.some(word => title.includes(word));

            const isEmptyPR = pr.changed_files === 0 || pr.additions === 0;

            if (![isFromFork, isLikelySync, isEmptyPR].every(Boolean)) {
                return;
            }
            const baseRepoFullName = pr.base.repo.full_name;
            const baseBranchName = pr.base.ref;

            const message = `
Hi! 👋 It looks like you're trying to sync your fork's \`${baseBranchName}\` branch with the \`${baseRepoFullName}\` repository.

This pull request was likely opened by mistake. To sync your fork's \`${baseBranchName}\` branch, please follow these steps in your local clone of your fork:

1.  **Add the upstream repository as a remote (if you haven't already):**
    \`\`\`bash
    git remote add upstream https://github.com/${baseRepoFullName}.git
    \`\`\`
    *(You only need to do this once per clone.)*

2.  **Fetch the latest changes from the upstream repository:**
    \`\`\`bash
    git fetch upstream
    \`\`\`

3.  **Check out your local branch that corresponds to \`${baseBranchName}\`:**
    *(This is typically also named \`${baseBranchName}\` in your fork. If it's different, use your fork's branch name.)*
    \`\`\`bash
    git checkout ${baseBranchName}
    \`\`\`

4.  **Merge the changes from \`upstream/${baseBranchName}\` into your local branch:**
    \`\`\`bash
    git merge upstream/${baseBranchName}
    \`\`\`
    *(This brings your local branch up to date with the upstream.)*

5.  **Push the updated branch to your fork on GitHub:**
    \`\`\`bash
    git push origin ${baseBranchName}
    \`\`\`

Closing this PR to keep our queue clean. Thank you! 💙
If this was not a mistake, please feel free to reopen this pull request and clarify its purpose.`.trim();

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });
